export type SiteLanguage = 'zh' | 'en'

export const SITE_LANGUAGE_KEY = 'hongcai_language'

const english: Record<string, string> = {
  '首页': 'Home',
  '产品中心': 'Products',
  '所有产品': 'All products',
  '产品类别': 'Product category',
  '产品筛选条件': 'Product filters',
  '卫浴五金': 'Bathroom hardware',
  '安装及配件': 'Installation parts',
  '卫浴产品、卫浴五金、安装及配件，先按品类筛选，再进入型号、材质与报价沟通。': 'Filter sanitaryware, bathroom hardware and installation parts before discussing models, materials and quotations.',
  '询价': 'Enquire',
  '产品电子图册': 'Product catalogue',
  '产品图册正在整理，正式文件上传后即可下载。': 'The catalogue is being prepared and will be available once the final file is uploaded.',
  '下载图册（PDF）': 'Download catalogue (PDF)',
  '快速询价': 'Quick enquiry',
  '提交需求后，我们会根据产品方向与联系方式进一步沟通。': 'Share your requirements and we will follow up using your contact details.',
  '联系电话': 'Phone',
  '请输入联系电话': 'Enter your phone number',
  '搜索或选择产品': 'Search or choose a product',
  '提交询价': 'Submit enquiry',
  '询价已提交，我们会尽快与您联系。': 'Your enquiry has been submitted. We will contact you shortly.',
  '请先填写姓名、公司和联系电话，再提交询价。': 'Enter your name, company and phone before submitting the enquiry.',
  '请按提示修改表单信息后再提交。': 'Please correct the fields marked below before submitting.',
  '请填写姓名。': 'Please enter your name.',
  '姓名需填写 2–30 个中文或英文字符。': 'Enter 2–30 Chinese or English characters for your name.',
  '请填写公司名称。': 'Please enter your company name.',
  '公司名称需填写 2–80 个字符。': 'Enter a company name between 2 and 80 characters.',
  '请填写联系电话。': 'Please enter your phone number.',
  '联系电话需填写 7–15 位数字，可包含 +、空格、括号或短横线。': 'Enter 7–15 phone digits; spaces, +, parentheses and hyphens are allowed.',
  '请选择或填写感兴趣的产品。': 'Please choose or enter a product of interest.',
  '服务支持': 'Service support',
  '专业团队': 'Professional team',
  '一对一服务': 'Dedicated service',
  '快速响应': 'Fast response',
  '24小时内回复': 'Reply within 24 hours',
  '项目支持': 'Project support',
  '提供定制方案': 'Tailored solutions',
  '关于我们': 'About us',
  '新闻动态': 'News',
  '案例展示': 'Cases',
  '联系我们': 'Contact us',
  '专注卫浴五金产品供应': 'Bathroom & hardware supply',
  '品质连接更多可能': 'Quality connects possibilities',
  '全球卫浴五金合作伙伴': 'Global bathroom & hardware partner',
  '让更好的卫浴': 'Better bathroom products',
  '走向更广阔的世界': 'for a wider world',
  '按采购方向，快速找到产品': 'Find the right products by sourcing need',
  '卫浴产品': 'Sanitaryware',
  '其他产品': 'Other products',
  '品质卫浴，舒适生活空间': 'Quality bathroom products for better spaces',
  '多元五金，满足更多场景需求': 'Versatile hardware for more applications',
  '产品分类': 'Product categories',
  '全部产品': 'All products',
  '材质': 'Material',
  '全部材质': 'All materials',
  '不锈钢': 'Stainless steel',
  '铜': 'Brass',
  '铝合金': 'Aluminium alloy',
  '陶瓷': 'Ceramic',
  '待确认': 'Pending confirmation',
  '默认排序': 'Default order',
  '按类别': 'By category',
  '按材质': 'By material',
  '产品排序': 'Product sorting',
  '示意素材 / 待替换': 'Illustrative visual / to be replaced',
  '示例款 / 待补型号': 'Sample style / model pending',
  '表面': 'Finish',
  '当前筛选暂无产品，请更换分类或材质。': 'No products match these filters. Try another category or material.',
  '面盆龙头': 'Basin faucets',
  '花洒套装': 'Shower sets',
  '淋浴花洒套装': 'Shower set collection',
  '坐便器': 'Toilets',
  '坐便器系列': 'Toilet collection',
  '浴室柜': 'Bathroom cabinets',
  '浴室柜组合': 'Bathroom cabinet sets',
  '厨房龙头': 'Kitchen faucets',
  'LTA-822 花洒': 'LTA-822 shower set',
  '卫浴挂件': 'Bathroom accessories',
  '毛巾架': 'Towel racks',
  '置物架': 'Shelves',
  '阀门配件': 'Valve fittings',
  '三角阀': 'Angle valves',
  '进水阀': 'Inlet valves',
  '排水配件': 'Drainage fittings',
  '地漏': 'Floor drains',
  '安装配件': 'Installation fittings',
  '电镀': 'Chrome plated',
  '拉丝': 'Brushed',
  '釉面': 'Glazed',
  '了解我们，也了解合作依据': 'Know who we are and how we work',
  '公司简介': 'Company profile',
  '认识红财万富，也认识我们的品牌': 'Know Hongcai Wanfu and the thinking behind our brand',
  '品牌文化': 'Brand culture',
  '让真实、清晰的产品信息，成为长期合作的起点。': 'Let clear, authentic product information become the starting point for long-term cooperation.',
  '荣誉资质': 'Qualifications and honours',
  '只呈现真实、有效、可核验的企业与产品资料。': 'Only authentic, valid and verifiable company and product documents are presented.',
  '企业 VI': 'Corporate identity',
  '统一品牌标志、标准色与中英文名称的使用方式。': 'A consistent system for the brand mark, colours and Chinese and English names.',
  '检测报告': 'Test reports',
  '常见问题解答': 'Frequently asked questions',
  '专注品质卫浴与五金，服务全球合作伙伴': 'Focused on quality bathroom products and hardware for global partners',
  '红财万富专注于卫浴产品、卫浴五金与安装配件的供应，面向批发、外贸与工程采购客户，按照真实采购流程整理产品信息和合作入口。': 'Hongcai Wanfu supplies sanitaryware, bathroom hardware and installation parts for wholesale, export and project buyers, with information and enquiry paths organised around real sourcing workflows.',
  '我们希望客户能够从产品范围、型号、材质与应用方向开始，更顺畅地进入样品、报价和项目沟通。公司规模、生产能力与认证信息将在取得正式资料后补充。': 'We help buyers move from product scope, model, material and application needs into sample, quotation and project discussions. Company scale, production capacity and certification details will be added once verified materials are available.',
  '我们的业务重点': 'Our product focus',
  '以三大产品方向组织信息，让客户更快确认采购范围。': 'Three product directions help buyers confirm their sourcing scope faster.',
  '围绕龙头、花洒、坐便器与浴室柜等核心品类，帮助客户按场景、型号与材质建立选品范围。': 'Core ranges include faucets, shower systems, toilets and bathroom cabinets, organised by application, model and material.',
  '整理挂件、置物与功能五金等产品信息，为批发、外贸与工程采购提供清晰的沟通基础。': 'Accessories, storage and functional hardware are documented clearly for wholesale, export and project sourcing.',
  '覆盖阀门、排水和安装配套方向，方便客户在主体产品之外同步确认所需配件。': 'Valves, drainage parts and installation fittings help buyers confirm the accessories needed alongside main products.',
  '合作资料与沟通依据': 'Cooperation information',
  '先呈现已确认的信息，其他内容在取得真实资料后逐步补充。': 'Verified information comes first; supporting materials are added as authentic documents become available.',
  '产品资料': 'Product information',
  '逐步完善产品图片、型号、材质、规格和包装信息，方便采购人员进行初步筛选。': 'Product images, models, materials, specifications and packaging details are being organised for initial sourcing review.',
  '持续整理中': 'Being organised',
  '品质文件': 'Quality documents',
  '检测报告、认证与质量文件只在取得可核验资料后展示，避免使用未经确认的信息。': 'Test reports, certifications and quality documents are shown only after verifiable files are available.',
  '以正式文件为准': 'Official documents apply',
  '采购沟通': 'Sourcing communication',
  '围绕产品方向、数量、市场与项目周期收集需求，让选品、样品和报价沟通更集中。': 'Requirements are collected by product direction, quantity, market and project schedule to keep samples and quotations focused.',
  '支持在线询价': 'Online enquiries available',
  '目前围绕卫浴产品、卫浴五金、安装及配件三大方向整理，包括花洒、龙头、坐便器、浴室柜，以及毛巾架、置物架、三角阀、进水阀等。': 'The range is organised across sanitaryware, bathroom hardware and installation parts, including showers, faucets, toilets, bathroom cabinets, towel racks, shelves, angle valves and inlet valves.',
  '红财万富专注于卫浴及五金产品的供应，面向批发、外贸与工程采购客户，提供清晰的产品选择与沟通方案。': 'Hongcai Wanfu supplies bathroom products and hardware for wholesale, export and project buyers, with a clear path from product selection to sourcing communication.',
  '我们重视长期主义，与合作伙伴共同成长，以稳定的产品与专业服务助力更多项目落地。公司规模、生产能力与认证信息将在取得正式资料后补充。': 'We value long-term partnerships and support project delivery with dependable products and professional service. Company scale, production capacity and certification details will be added once verified materials are available.',
  '以下为检测报告版式示例，正式文件与检测结论需以公司提供的真实资料为准。': 'The documents below are layout samples. Official files and findings must be replaced with verified company materials.',
  '陶瓷卫浴系列': 'Ceramic sanitaryware',
  '龙头五金系列': 'Faucet hardware',
  '淋浴花洒系列': 'Shower systems',
  '产品检测报告': 'Product test report',
  '示例文件 / 待替换': 'Sample document / to be replaced',
  '示例文件 / 待核验': 'Sample document / unverified',
  '待补充报告': 'Report pending',
  '以下为合作过程中经常被问到的问题，具体产品与订单信息以双方确认结果为准。': 'Common questions about cooperation. Product and order details remain subject to confirmation by both parties.',
  '我们的产品范围包括哪些？': 'What products do you supply?',
  '目前围绕卫浴产品与其他产品两大方向整理，包括花洒、龙头、坐便器、浴室柜，以及毛巾架、置物架、三角阀、进水阀等。': 'The current range covers sanitaryware and related products, including showers, faucets, toilets, bathroom cabinets, towel racks, shelves, angle valves and inlet valves.',
  '如何获取报价？可以提供样品吗？': 'How can I request a quote or sample?',
  '请通过联系我们页面提交产品、数量、目标市场和交期需求。样品与报价条件需要根据具体产品确认。': 'Use the Contact page to send the product, quantity, target market and delivery requirements. Sample and quotation terms depend on the selected product.',
  '产品如何包装？': 'How are products packed?',
  '包装方式需要结合具体型号、数量及运输方式确认；现阶段页面不预设未经核实的包装承诺。': 'Packaging depends on the model, quantity and transport method. No unverified packaging commitment is presented at this stage.',
  '一般的交货周期是多少？': 'What is the typical lead time?',
  '交期由产品、数量、包装及订单排期共同决定，收到采购清单后再给出准确答复。': 'Lead time depends on product, quantity, packaging and production scheduling. An accurate answer follows review of the sourcing list.',
  '是否支持定制？': 'Do you support customisation?',
  '可提交颜色、标识、包装或产品组合需求，具体可行性以实际评估结果为准。': 'You may submit colour, branding, packaging or product-bundle requirements. Feasibility is subject to assessment.',
  '记录公司进展，也关注行业变化': 'Company updates and industry perspectives',
  '全部': 'All',
  '公司新闻': 'Company news',
  '行业资讯': 'Industry insights',
  '新闻分类': 'News categories',
  '分页': 'Pagination',
  '从产品选择，到最终落地': 'From product selection to project delivery',
  '全部案例': 'All cases',
  '客户案例': 'Customer cases',
  '项目案例': 'Project cases',
  '落地效果': 'Installed results',
  '案例分类': 'Case categories',
  '项目类型': 'Project type',
  '项目地点': 'Project location',
  '供应产品': 'Products supplied',
  '待填写': 'To be provided',
  '案例资料待补充': 'Case details pending',
  '现代公共空间卫浴项目': 'Modern public-space bathroom concept',
  '公共空间': 'Public space',
  '卫浴五金、感应龙头、挂件、阀门配件': 'Bathroom hardware, sensor faucets, accessories and valve fittings',
  '酒店卫浴配套场景': 'Hotel bathroom supply concept',
  '酒店空间': 'Hotel space',
  '淋浴五金、卫浴挂件、地漏': 'Shower hardware, bathroom accessories and floor drains',
  '商业综合体场景': 'Commercial complex concept',
  '商业空间': 'Commercial space',
  '龙头、卫浴挂件、五金配件': 'Faucets, bathroom accessories and hardware fittings',
  '住宅精装场景': 'Residential fit-out concept',
  '住宅空间': 'Residential space',
  '淋浴五金、卫浴挂件、开关面板': 'Shower hardware, bathroom accessories and switch panels',
  '办公空间场景': 'Office bathroom concept',
  '办公空间': 'Office space',
  '水龙头、卫浴挂件、五金配件': 'Faucets, bathroom accessories and hardware fittings',
  '酒店、商业、住宅等工程项目合作咨询': 'Sourcing enquiries for hotel, commercial and residential projects',
  '我们为各类空间提供专业的卫浴五金采购沟通方案': 'We support bathroom and hardware sourcing communication for a range of spaces.',
  '立即咨询': 'Enquire now',
  '告诉我们，你正在采购什么': 'Tell us what you are sourcing',
  '联系方式': 'Contact details',
  '欢迎通过以下渠道联系红财万富，正式联系方式确认后将及时更新。': 'Contact Hongcai Wanfu through the channels below. Confirmed contact details will be updated promptly.',
  '地理位置': 'Location',
  '公司地址和地图信息确认后，将在这里提供准确的到访指引。': 'Accurate visiting directions will be provided here once the address and map details are confirmed.',
  '与红财万富取得联系': 'Get in touch with Hongcai Wanfu',
  '我们专注于卫浴及五金产品，为批发商、工程商、品牌商和零售渠道提供产品与服务。欢迎通过以下方式联系，或提交右侧表单。': 'We focus on bathroom products and hardware for wholesalers, contractors, brands and retail channels. Contact us directly or send the enquiry form.',
  '电话': 'Phone',
  '邮箱': 'Email',
  '微信 / WhatsApp': 'WeChat / WhatsApp',
  '办公 / 展厅地址': 'Office / showroom address',
  '待补充': 'Pending',
  '工作时间：待补充': 'Business hours: pending',
  '欢迎发送产品需求、项目资料或合作咨询': 'Send product requirements, project information or partnership enquiries',
  '添加我们，随时沟通': 'Add us for direct communication',
  '欢迎预约到访': 'Visits by appointment are welcome',
  '提交采购需求': 'Send a sourcing enquiry',
  '请填写以下信息，让我们更好地了解您的需求。': 'Share a few details so we can understand your requirements.',
  '姓名 *': 'Name *',
  '公司 *': 'Company *',
  '邮箱 *': 'Email *',
  '电话 / WhatsApp *': 'Phone / WhatsApp *',
  '采购方向 *': 'Sourcing route *',
  '感兴趣的产品 *': 'Products of interest *',
  '数量': 'Quantity',
  '需求说明': 'Requirements',
  '请输入姓名': 'Enter your name',
  '请输入公司名称': 'Enter your company name',
  '请输入邮箱地址': 'Enter your email address',
  '请输入电话号码': 'Enter your phone number',
  '请选择': 'Select an option',
  '批发与经销': 'Wholesale & distribution',
  '外贸采购': 'Export sourcing',
  '工程项目': 'Project sourcing',
  '请输入预计采购数量': 'Enter the estimated quantity',
  '请详细描述采购需求、应用场景或项目信息': 'Describe the products, application or project requirements',
  '演示提交成功。正式上线后将连接后台与邮件通知。': 'Demo submitted. The live site will connect this form to the admin system and email notifications.',
  '我们会妥善保管您的信息，仅用于商务沟通。': 'Your information will be used only for business communication.',
  '我们的位置': 'Our location',
  '欢迎莅临参观洽谈\n与我们面对面交流': 'Visit us by appointment\nand meet our team',
  '地图示意 / 待替换': 'Map placeholder / to be replaced',
  '这里将显示公司位置地图（待补充）': 'The company location map will appear here (pending).',
  '三种采购对接方式': 'Three ways to start sourcing',
  '选择最适合您的方式，快速开启合作。': 'Choose the most suitable route to begin.',
  '产品目录': 'Product catalogue',
  '获取最新产品目录\n了解产品系列与解决方案': 'Request the latest catalogue\nand explore available product ranges',
  '样品申请': 'Sample request',
  '申请产品样品\n亲身体验产品品质与工艺': 'Request product samples\nto review quality and workmanship',
  '项目询价': 'Project quotation',
  '提供项目需求\n获取针对性的产品方案与报价': 'Share project requirements\nand request a tailored product proposal and quote',
  '搜索': 'Search',
  '关闭搜索': 'Close search',
  '打开导航': 'Open navigation',
  '关闭导航': 'Close navigation',
  '主导航': 'Main navigation',
  '页脚导航': 'Footer navigation',
  '搜索产品、分类或页面': 'Search products, categories or pages',
  '搜索产品型号、关键词…': 'Search model or keyword…',
  '没有找到相关内容，请换一个关键词。': 'No matching content. Try another keyword.',
  '网站首页': 'Website home',
  '公司与行业资讯': 'Company and industry updates',
  '客户、项目与落地效果': 'Customer, project and installation cases',
  '采购与合作咨询': 'Sourcing and partnership enquiries',
  '卫浴五金与安装配件': 'Bathroom hardware and installation fittings',
  '切换到中文': 'Switch to Chinese',
  '切换到英文': 'Switch to English',
  '卫浴产品场景示意': 'Illustrative bathroom product scene',
  '按采购逻辑，找到对应产品': 'Find the right product by sourcing logic',
  '根据采购需求找到合适的商品': 'Find the right products for your sourcing needs',
  '产品目录示意': 'Illustrative product catalogue',
  '图册待上传': 'Catalogue pending upload',
  '样品申请示意': 'Illustrative sample request',
  '项目询价示意': 'Illustrative project quotation'
}

export function useSiteLanguage() {
  const languageCookie = useCookie<SiteLanguage>(SITE_LANGUAGE_KEY, {
    default: () => 'zh',
    sameSite: 'lax',
    maxAge: 60 * 60 * 24 * 365
  })
  const language = useState<SiteLanguage>('site-language', () => languageCookie.value === 'en' ? 'en' : 'zh')

  useHead(() => ({ htmlAttrs: { lang: language.value === 'en' ? 'en' : 'zh-CN' } }))

  const setLanguage = (next: SiteLanguage) => {
    language.value = next
    languageCookie.value = next
    if (import.meta.client) {
      localStorage.setItem(SITE_LANGUAGE_KEY, next)
      document.documentElement.lang = next === 'en' ? 'en' : 'zh-CN'
    }
  }

  const toggleLanguage = () => setLanguage(language.value === 'zh' ? 'en' : 'zh')
  const t = (source: string, translation?: string) => language.value === 'en' ? (translation || english[source] || source) : source

  return { language, setLanguage, toggleLanguage, t }
}
